# MATH 210 Introduction to Mathematical Computing

## October 5, 2018

* Python Objects and Classes
* More about NumPy Arrays
* Examples: Optimization

## Python Objects

Without getting too far into it, let's introduce some ideas from object-oriented programming. [Everything in Python is an object](https://stackoverflow.com/questions/865911/is-everything-an-object-in-python-like-ruby). An object is a logical bundle of data (attributes) and functionality (methods). For example, we can create a list:

In [1]:
x = [3,2,-5]

The data in the list object are the entries. We can interact with the data using methods.

In [2]:
x.append(-7)

In [3]:
x

[3, 2, -5, -7]

In [4]:
x.pop(1)

2

In [5]:
x

[3, -5, -7]

## NumPy arrays

In [6]:
import numpy as np

The NumPy package defines the [NumPy array object](https://docs.scipy.org/doc/numpy-1.15.1/reference/arrays.html). These are arrays built for fast computation.

In [7]:
A = np.array([[2,3],[-1,4]])

In [8]:
print(A)

[[ 2  3]
 [-1  4]]


We can access [attributes](https://docs.scipy.org/doc/numpy-1.15.1/reference/arrays.ndarray.html#array-attributes) of the NumPy array object `A`.

In [9]:
A.ndim

2

In [10]:
A.shape

(2, 2)

In [11]:
A.size

4

We can execute [methods](https://docs.scipy.org/doc/numpy-1.15.1/reference/arrays.ndarray.html#array-methods) (functions) on the object. Object-oriented programming allows use to chain several methods together.

In [12]:
A.transpose().transpose()

array([[ 2,  3],
       [-1,  4]])

In [13]:
A.max()

4

In [14]:
A.min()

-1

In [15]:
A.argmax()

3

There are also [NumPy functions](https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html) for these operations.

In [16]:
np.max(A)

4

In [17]:
np.min(A)

-1

In [18]:
np.argmax(A)

3

Compare these 2 cases to see the difference between object-oriented programming and functional programming.

In [19]:
A.transpose().transpose()

array([[ 2,  3],
       [-1,  4]])

In [20]:
np.transpose(np.transpose(A))

array([[ 2,  3],
       [-1,  4]])

## Root Finding

Let's get back to computation and use NumPy arrays and functions.

Find a solution of the equation $x = \cos(x)$ using Newton's method.

Apply Newton's method to $f(x) = x - \cos(x)$. Then $f'(x)=1 + \sin(x)$. Let's choose $x_0 = 0.5$.

In [21]:
xn = 0.5
max_iter = 7
for n in range(0,max_iter):
    xn = xn - (xn - np.cos(xn))/(1 + np.sin(xn))
print(xn)

0.739085133215


## Brute Force Method

The brute force method to find a solution of $f(x)=0$ simply computes $f(x)$ for an array of $x$ values and returns the smallest $|f(x)|$.

In [22]:
x = np.linspace(0.7,0.8,1000)
y = x - np.cos(x)
i = np.argmin(np.abs(y))
x[i]

0.739039039039039