# MATH 210 Introduction to Mathematical Computing

## November 2, 2018

* NumPy arrays: reshape, indexing and slicing
* Linear systems

In [1]:
import numpy as np
import scipy.linalg as la

## NumPy arrays

Recall, every NumPy array has a number of dimensions. We need to make sure that we know how many dimensions our arrays have.

In [2]:
w = np.array([1,-2,4,7])

In [3]:
print(w)

[ 1 -2  4  7]


In [4]:
w.ndim

1

In [5]:
w.shape

(4,)

If we want to make the 1D array into a 2D column vector, then we can reshape it.

In [6]:
w.reshape(4,1)

array([[ 1],
       [-2],
       [ 4],
       [ 7]])

In [7]:
w

array([ 1, -2,  4,  7])

In [8]:
w = w.reshape(4,1)

In [9]:
w

array([[ 1],
       [-2],
       [ 4],
       [ 7]])

A 1D array only needs one index to specify a entry.

In [10]:
a = np.array([0,1,-4,7,8])

In [11]:
a[4]

8

A 2D array requires 2 indices to specify an entry.

In [12]:
M = np.random.randint(-9,10,(8,11))

In [13]:
print(M)

[[-2 -7 -7 -6 -8  2 -4  7 -6 -6  5]
 [-2  6 -8 -5  5 -6  7 -3 -3  2  5]
 [ 4  6  0  8 -8  8 -6 -2 -7 -8  9]
 [ 1 -6  9 -7  7 -5 -9 -7  7 -8  6]
 [ 2 -9 -3 -4  9 -5 -7 -9 -2  2  5]
 [-1 -8  1  6  9 -5 -4 -8 -3 -1  3]
 [-3 -4 -2  6  8 -3  3  7  5 -6 -8]
 [-8 -2 -5  1  6 -9  5  8 -6  1  4]]


In [14]:
M[4,1]

-9

In [15]:
col = M[:,9]

In [16]:
print(col)

[-6  2 -8 -8  2 -1 -6  1]


We can stack arrays together to create bigger arrays.

In [17]:
c1 = np.array([1,1,-2])
c2 = np.array([0,1,-1])
c3 = np.array([1,1,1])
A = np.column_stack([c1,c2,c3])

In [18]:
A

array([[ 1,  0,  1],
       [ 1,  1,  1],
       [-2, -1,  1]])

In [19]:
N = np.array([c1,c2,c3])

In [20]:
print(N)

[[ 1  1 -2]
 [ 0  1 -1]
 [ 1  1  1]]


## Linear Systems

A [linear system of equations](https://en.wikipedia.org/wiki/System_of_linear_equations) is $Ax = b$ where $A$ is a m by n matrix, $x$ is n by 1 column vector, and $b$ is a m by 1 column vector.

To solve a system, we can use the function `scipy.linalg.solve`.

In [21]:
A = np.array([[2,1],[1,1]])
print(A)

[[2 1]
 [1 1]]


In [22]:
b = np.array([1,-1]).reshape(2,1)
print(b)

[[ 1]
 [-1]]


In [23]:
x = la.solve(A,b)

In [24]:
print(x)

[[ 2.]
 [-3.]]


Or we can compute the inverse:

In [25]:
Ainv = la.inv(A)
print(Ainv)

[[ 1. -1.]
 [-1.  2.]]


And multiply $A^{-1}b$ to solve for $x$:

In [26]:
x = Ainv @ b

In [27]:
print(x)

[[ 2.]
 [-3.]]


It's a bad idea to use the inverse if $A$ is large. Let's create a randomg

In [28]:
N = 1000
A = np.random.rand(N,N)
b = np.random.rand(N,1)

In [29]:
A[:3,:3]

array([[ 0.70583519,  0.24313229,  0.44847959],
       [ 0.65626785,  0.14119294,  0.95101522],
       [ 0.78665567,  0.18258646,  0.93674084]])

In [30]:
b[:4,:]

array([[ 0.88200832],
       [ 0.44003805],
       [ 0.19728028],
       [ 0.52501379]])

In [31]:
%%timeit
x = la.solve(A,b)

443 ms ± 47.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [32]:
%%timeit
x = la.inv(A) @ b

The slowest run took 4.74 times longer than the fastest. This could mean that an intermediate result is being cached.
1.29 s ± 840 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
