# MATH 210 Introduction to Mathematical Computing

## October 29, 2018

* Linear Algebra with SciPy

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Linear algebra with SciPy

The [NumPy](http://www.numpy.org/) package gives us NumPy arrays and mathematical functions. SciPy is a library with many mathematical functions. We use `scipy.linalg` for linear algebra computations. See the [documentation](https://docs.scipy.org/doc/scipy/reference/linalg.html).

The standard convention is:

In [2]:
import scipy.linalg as la

## NumPy arrays

We use NumPy to create arrays. We need to keep track of the shape, size and dimensions of our arrays. It can get a bit confusing. And it's a bit different from MATLAB.

Let' do a quick review of NumPy arrays. Create a 1D (one-dimensional) NumPy array and check its dimensions and shape and size.

In [3]:
a = np.array([1,3,-2,1])

In [4]:
print(a)

[ 1  3 -2  1]


In [5]:
a.ndim

1

In [6]:
a.shape

(4,)

In [7]:
a.size

4

Create a 2D (two-dimensional) NumPy array (ie. matrix). Check its dimensions, shape and size.

In [8]:
M = np.array([[1,2],[3,7],[-1,5]])

In [9]:
print(M)

[[ 1  2]
 [ 3  7]
 [-1  5]]


In [10]:
M.ndim

2

In [11]:
M.shape

(3, 2)

In [12]:
M.size

6

Select a row or column from a 2D NumPy array, we get a 1D array.

In [13]:
col = M[:,1] 

In [14]:
print(col)

[2 7 5]


In [15]:
col.ndim

1

In [16]:
col.shape

(3,)

Create a 3D NumPy array and check it's shape and size:

In [17]:
C = np.arange(0,8).reshape(2,2,2)

In [18]:
print(C)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [19]:
C.shape

(2, 2, 2)

Create a 2D column vector:

In [20]:
column = np.array([[2],[7],[5]])
print(column)

[[2]
 [7]
 [5]]


In [21]:
column.shape

(3, 1)

Variables `col` and `column` are different objects even though they have the "same" data.

In [22]:
print(col)

[2 7 5]


In [23]:
col.shape

(3,)

## Matrix multiplication

Recall that arithmetic array operations `*` and `**` are performed elementwise:

In [24]:
M = np.array([[1,1],[1,2]])
print(M)

[[1 1]
 [1 2]]


In [25]:
M*M

array([[1, 1],
       [1, 4]])

In [26]:
M**2

array([[1, 1],
       [1, 4]])

We use the `@` symbol for matrix multiplication:

In [27]:
M@M

array([[2, 3],
       [3, 5]])

There's no symbol for matrix powers. There is a function.

In [28]:
from numpy.linalg import matrix_power as mpow

In [29]:
mpow(M,2)

array([[2, 3],
       [3, 5]])

In [30]:
mpow(M,5)

array([[34, 55],
       [55, 89]])

In [31]:
M@M@M@M@M

array([[34, 55],
       [55, 89]])

In [32]:
M@M@M

array([[ 5,  8],
       [ 8, 13]])

In [33]:
mpow(M,3)

array([[ 5,  8],
       [ 8, 13]])